apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-app-deployment
  labels:
    app: boardgame-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boardgame-app
  template:
    metadata:
      labels:
        app: boardgame-app
    spec:
      containers:
        - name: boardgame-app-container
          image: boardgame-app
          imagePullPolicy: Never
          ports:
            - containerPort: 4040
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:mem:testdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
