apiVersion: v1
kind: Service
metadata:
  name: boardgame-app-service
spec:
  type: NodePort
  selector:
    app: boardgame-app
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
      nodePort: 30000
